#!/bin/bash

# Install script for samftp on macOS

# Step 1: Install Python if not already installed
# TODO: Add commands to check and install Python if needed

# Step 2: Install required packages using pip
pip install --user requests~=2.26.0
pip install --user beautifulsoup4==4.12.2
pip install --user pyfzf~=0.3.1

# Step 3: Copy the script to the desired location
DESTINATION_FOLDER="$HOME/.local/bin"
cp "samftp" $DESTINATION_FOLDER

# Step 4: Add the shebang for Python 3 to the script
sed -i '' '1s|^|#!/usr/bin/env python3\n|' $DESTINATION_FOLDER/samftp

echo Installation completed.
